# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvrnormArma <- function(n, mu, sigma) {
    .Call('_spruce_mvrnormArma', PACKAGE = 'spruce', n, mu, sigma)
}

rtn <- function(a, b, mu, sig) {
    .Call('_spruce_rtn', PACKAGE = 'spruce', a, b, mu, sig)
}

update_t <- function(ts, k, k_inds, Ak, xnk, Sigmak, Y, munk, a, b) {
    .Call('_spruce_update_t', PACKAGE = 'spruce', ts, k, k_inds, Ak, xnk, Sigmak, Y, munk, a, b)
}

update_z <- function(zs, Y, mun, Sigma, pi, classes) {
    .Call('_spruce_update_z', PACKAGE = 'spruce', zs, Y, mun, Sigma, pi, classes)
}

update_z_PG <- function(zs, Y, mun, Sigma, Pi, classes) {
    .Call('_spruce_update_z_PG', PACKAGE = 'spruce', zs, Y, mun, Sigma, Pi, classes)
}

update_z_MSN <- function(zs, Y, t, mun, xin, Sigma, pi, classes) {
    .Call('_spruce_update_z_MSN', PACKAGE = 'spruce', zs, Y, t, mun, xin, Sigma, pi, classes)
}

