# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
mvrnormArma <- function(n, mu, sigma) {
    .Call(`_spruce_mvrnormArma`, n, mu, sigma)
}

#' @export
update_z <- function(zs, Y, mun, Sigma, pi, classes) {
    .Call(`_spruce_update_z`, zs, Y, mun, Sigma, pi, classes)
}

